export interface Player {
    id: string,
    nickname: string,
    email: string,
    ongoingGameId?: string,
    ongoingTournamentId?: string,
    ongoingSpecialGameId?: string,
    eloRankedBlitz: number,
    eloSpecialBlitz: number,
    eloRankedBullet: number,
    eloSpecialBullet: number,
    eloRankedRapid: number,
    eloSpecialRapid: number,
    eloRankedClassic: number,
    eloSpecialClassic: number,
    eloRankedUnlimited: number,
    eloSpecialUnlimited: number,
    role: string,
    createdAt: Date,
    editedAt: Date,
    deletedAt: Date,
};
